# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9afb51f5d57cb42a53e43c1795f5acdfc466b0a9d8dfbb4d5a9affad60b6356562b7d98d458ff87c3f97c36e013627fc361363b8db1d3c9eb5133eda0bb7017

test:
  secret_key_base: a249b7d66918f84dc2d00592de5a967aa2e04188c484d555c6e10ba4537d329bfff17f12aa7de7c876fd451aac10b48f6c6bc424e30c7d490d9d148bfc26ca9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
